AWSTemplateFormatVersion: 2010-09-09
Resources:
  MorningFacilitatorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./release/app.zip
      FunctionName: MorningFacilitatorFunction
      Handler: index.handler
      Runtime: nodejs12.x
      Role: "{lambda arn}"
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TZ: Asia/Tokyo
          MEMBER: "@yamada,@yamamoto,@yamashita,@yamagami,@yamsuda"
          SLACK_TOKEN: "{slack api token}"
          SLACK_CHANNEL: "{slack channel}"

  FacilitatorHistory:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FacilitatorHistory
      AttributeDefinitions:
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: status
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  FacilitatorEventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: FacilitatorEventsRule
      ScheduleExpression: 'cron(45 0 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt MorningFacilitatorFunction.Arn
          Id: lambda
          
  MorningFacilitatorPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MorningFacilitatorFunction
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt FacilitatorEventsRule.Arn
